#!/usr/bin/env python3
"""Regenerate the ``graphemes`` and ``allophones`` blocks of ``vi.json``.

Vietnamese is written in a rime-based orthography: a quốc ngữ syllable is an
onset spelling, a rime (vần) spelling, and a tone diacritic that sits on one
letter inside the rime. The rime is the unit whose pronunciation is
predictable — ⟨anh⟩ is [ɛŋ] and ⟨ong⟩ is [ɔŋ͡m] whatever precedes them — so
the spec maps whole toned rimes rather than single letters, and this script
composes that table from the nucleus inventory, the coda inventory, the
allophony that relates them, and the tone paradigm.

Every phonetic value comes from Kirby, J. P. (2011), "Vietnamese (Hanoi
Vietnamese)", *Journal of the International Phonetic Association* 41(3),
381–392 — the IPA Illustration for the variety both benchmark gold sets
transcribe. The facts used here, each stated in that article:

* Nine vowel qualities /i e ɛ ɯ ɤ a u o ɔ/ and three falling diphthongs
  /iə ɯə uə/; length is distinctive only for /a/ and /ɤ/, which is what
  ⟨ă⟩ and ⟨â⟩ spell.
* Eight coda segments: /p t k m n ŋ j w/.
* Velar fronting: /ŋ k/ after /i e ɛ/ are pre-velar, not palatal — ⟨canh⟩
  is [kɛŋ̟], ⟨sách⟩ [sɛk̟], ⟨kinh⟩ [kiŋ̟], ⟨xích⟩ [sik̟]. The pre-velar
  diacritic is a narrow detail; the spec writes plain /ŋ k/ and records the
  detail in the notes.
* Labial-velar finals: after the rounded vowels /u o ɔ/ the velar stops
  /k ŋ/ are doubly articulated [k͡p ŋ͡m] — ⟨ung⟩ [uŋ͡m], ⟨ông⟩ [oŋ͡m],
  ⟨ong⟩ [ɔŋ͡m], ⟨Úc⟩ [uk͡p], ⟨ốc⟩ [ok͡p], ⟨óc⟩ [ɔk͡p].
* Onsets: ⟨tr⟩ and ⟨ch⟩ are completely merged in modern Hanoi Vietnamese as
  /tɕ/; ⟨s⟩ and ⟨x⟩ as /s/; ⟨d gi r⟩ as /z/; ⟨g gh⟩ is the voiced velar
  fricative /ɣ/, not a stop; ⟨b đ⟩ are the implosives /ɓ ɗ/.
* Tone: eight tones, a six-tone paradigm in open or sonorant-final
  syllables and a **two-tone** paradigm in syllables closed by an
  unreleased oral stop, where only the sắc-spelled (D1) and nặng-spelled
  (D2) tones occur. That coda–tone restriction is why checked rimes below
  get two entries and every other rime gets six.
* Phonotactics: /j/ never follows the front vowels /i iə e ɛ/ and /w/ never
  follows the rounded vowels /u uə o ɔ/.

One orthographic rule is worth naming here because the ipa-dict gold
disagrees with it. After the onset ⟨gi⟩, a rime that begins with ⟨i⟩ is
written with a single ⟨i⟩ — ⟨gi⟩ + ⟨ìn⟩ is ⟨gìn⟩ and ⟨gi⟩ + ⟨iếng⟩ is
⟨giếng⟩. Both are generated by the same rule, so ⟨giếng⟩ is /ziəŋ/ and
⟨giết⟩ /ziət/, which is what Wiktionary gives for Hà Nội. Reading the
leftover letters ⟨êng êt⟩ as rimes in their own right instead yields
/zeŋ zet/, which is what the gold has; those rimes are otherwise
unattested, and the ⟨gi⟩ collapse is not special to ⟨i⟩ alone.

The Chao letters themselves are a NOTATION choice, not a claim beyond the
tone categories. Kirby transcribes the tones with IPA tone staves and gives
them by name and contour (level, mid falling, rising, low glottalized, low
falling, broken); the numeric renderings used here are the widely cited
Hanoi values and match the convention of the ipa-dict ``vi_N`` gold, so the
benchmark measures the tone CATEGORY the spec derives rather than a notation
gap. The categories are what the orthography decides, and they are decided
losslessly: all six tones are written.
"""
from __future__ import annotations

import json
import os
import unicodedata

DATA = os.path.join(os.path.dirname(__file__), "..", "orthography2ipa",
                    "data", "vi.json")

#: Onset spellings. ⟨q⟩ never stands alone in Vietnamese orthography, so
#: only the digraph ⟨qu⟩ is listed; ⟨p⟩ is initial only in loans.
ONSETS = {
    "b": "ɓ", "c": "k", "ch": "tɕ", "d": "z", "đ": "ɗ", "g": "ɣ",
    "gh": "ɣ", "gi": "z", "h": "h", "k": "k", "kh": "x", "l": "l",
    "m": "m", "n": "n", "ng": "ŋ", "ngh": "ŋ", "nh": "ɲ", "p": "p",
    "ph": "f", "qu": "kw", "r": "z", "s": "s", "t": "t", "th": "tʰ",
    "tr": "tɕ", "v": "v", "x": "s",
}

#: Nuclei whose rime, after the onset ⟨gi⟩, is written with a single ⟨i⟩:
#: ⟨gi⟩ + ⟨ìn⟩ is spelled ⟨gìn⟩ and ⟨gi⟩ + ⟨iếng⟩ is spelled ⟨giếng⟩. One
#: orthographic rule covers both, so both are generated the same way, and
#: ⟨giếng⟩ comes out /ziəŋ/ — the pronunciation Wiktionary gives for Hà
#: Nội — rather than the /zeŋ/ that falls out of reading the leftover
#: letters ⟨êng⟩ as a rime of their own. That leftover reading is what the
#: ipa-dict gold does, and the two disagree on this handful of words.
#:
#: ⟨ia⟩ is deliberately absent. The same collapse would spell ⟨gi⟩ + ⟨ia⟩
#: as ⟨gia⟩, which the orthography already uses for ⟨gi⟩ + ⟨a⟩ — and /za/
#: is what ⟨gia⟩ is; the /ziə/ rime is simply not written after ⟨gi⟩.
GI_MERGED_NUCLEI = ("i", "iê")

#: One coda is excluded, and only under the ⟨i⟩ nucleus: collapsing ⟨iu⟩
#: would spell ⟨giu⟩, which competes with the productive ⟨gi⟩ + ⟨u⟩-rime
#: spellings (⟨giúp⟩ /zup/, ⟨giũ⟩ /zu/). ⟨iêu⟩ collapses to ⟨giêu⟩, which
#: no ⟨u⟩-rime spells, so it is kept — ⟨giễu⟩ is /ziəw/.
GI_MERGE_EXCLUDED = {"i": ("u",)}

#: nucleus spelling → (IPA, index of the letter that carries the tone mark)
NUCLEI = {
    "a": ("a", 0), "ă": ("ă", 0), "â": ("ɤ̆", 0), "e": ("ɛ", 0),
    "ê": ("e", 0), "i": ("i", 0), "y": ("i", 0), "o": ("ɔ", 0),
    "ô": ("o", 0), "ơ": ("ɤ", 0), "u": ("u", 0), "ư": ("ɯ", 0),
    # Falling diphthongs. The closed-syllable spellings mark the second
    # letter (⟨tiếng⟩, ⟨buồn⟩, ⟨nước⟩), the open ones the first
    # (⟨mía⟩, ⟨múa⟩, ⟨mứa⟩).
    "iê": ("iə", 1), "yê": ("iə", 1), "uô": ("uə", 1), "ươ": ("ɯə", 1),
    "ia": ("iə", 0), "ya": ("iə", 0), "ua": ("uə", 0), "ưa": ("ɯə", 0),
    # ⟨oo⟩ is the long /ɔː/ of Kirby's [sɔːŋ] xoong (p. 384).
    "oo": ("ɔː", 1),
}

#: coda spelling → (IPA, closes the syllable with an oral stop)
CODAS = {
    "": ("", False),
    "p": ("p", True), "t": ("t", True), "c": ("k", True),
    "ch": ("k", True),
    "m": ("m", False), "n": ("n", False), "ng": ("ŋ", False),
    "nh": ("ŋ", False),
    "i": ("j", False), "y": ("j", False), "o": ("w", False),
    "u": ("w", False),
}

#: Attested coda sets per nucleus, i.e. the quốc ngữ rime inventory.
RIMES = {
    "a": ["", "p", "t", "c", "ch", "m", "n", "ng", "nh", "i", "y", "o", "u"],
    "ă": ["p", "t", "c", "m", "n", "ng"],
    "â": ["p", "t", "c", "m", "n", "ng", "y", "u"],
    "e": ["", "p", "t", "c", "m", "n", "ng", "o"],
    "ê": ["", "p", "t", "m", "n", "nh", "ch", "u"],
    "i": ["", "p", "t", "m", "n", "nh", "ch", "u"],
    # ⟨ynh ych yt yp⟩ are what is left of ⟨uynh uych uyt uyp⟩ once ⟨qu⟩
    # has taken the medial: ⟨Quỳnh⟩ is ⟨qu⟩ + ⟨ỳnh⟩ and ⟨quýt⟩ is ⟨qu⟩ +
    # ⟨ýt⟩. ⟨yc ym yn yng⟩ are not written.
    "y": ["", "nh", "ch", "t", "p"],
    "o": ["", "p", "t", "c", "m", "n", "ng", "i"],
    "ô": ["", "p", "t", "c", "m", "n", "ng", "i"],
    "ơ": ["", "p", "t", "m", "n", "i"],
    "u": ["", "p", "t", "c", "m", "n", "ng", "i"],
    # ⟨oo⟩ spells the long /ɔː/ of a handful of French loans and is
    # Kirby's named exception to the labial-velar rule: ⟨boong⟩ is
    # [ɓɔːŋ], not *[ɓɔŋ͡m].
    "oo": ["ng", "c"],
    "ư": ["", "t", "c", "m", "n", "ng", "i", "u"],
    "iê": ["p", "t", "c", "m", "n", "ng", "u"],
    "yê": ["m", "n", "ng", "t", "u"],
    "uô": ["t", "c", "m", "n", "ng", "i"],
    "ươ": ["p", "t", "c", "m", "n", "ng", "i", "u"],
    "ia": [""], "ya": [""], "ua": [""], "ưa": [""],
}

#: Rimes with a labial on-glide medial, spelled ⟨o⟩ before ⟨a ă e⟩ and ⟨u⟩
#: elsewhere. The medial is /w/ (Kirby writes it as a secondary labial
#: articulation on the onset, ⟨hoa⟩ [hʷa]).
MEDIAL_RIMES = {
    ("o", "a"): ["", "c", "ch", "i", "m", "n", "ng", "nh", "p", "t",
                 "y", "o"],
    ("o", "ă"): ["c", "m", "n", "ng", "p", "t"],
    ("o", "e"): ["", "n", "t", "o"],
    ("u", "â"): ["n", "ng", "t", "y"],
    ("u", "ê"): ["", "ch", "n", "nh", "t"],
    ("u", "y"): ["", "ch", "n", "nh", "p", "t", "u"],
    ("u", "ơ"): [""],
    ("u", "ya"): [""],
    ("u", "yê"): ["n", "t"],
}

#: tone name → (combining mark, unchecked Chao letters, checked value)
#: The unmarked ngang tone has no combining mark. Checked syllables carry
#: only the D1 (sắc-spelled) and D2 (nặng-spelled) tones.
TONES = [
    ("ngang", "", "˧˧", None),
    ("huyền", "̀", "˧˨", None),
    ("sắc", "́", "˨˦", "˦˥"),
    ("hỏi", "̉", "˧˩˨", None),
    ("ngã", "̃", "˧ˀ˥", None),
    ("nặng", "̣", "˨ˀ˩", "˨ˀ˩"),
]

FRONT_UNROUNDED = {"i", "iə", "e", "ɛ"}
#: /w/ never follows these (Kirby's phonotactic statement includes the
#: diphthong /uə/).
ROUNDED = {"u", "uə", "o", "ɔ"}
#: ...but the labial-velar coda rule is stated over the rounded
#: MONOPHTHONGS /u o ɔ/ only, which is why ⟨uống⟩ is [uəŋ], not *[uəŋ͡m].
ROUNDED_MONOPHTHONGS = {"u", "o", "ɔ"}


def rime_ipa(nucleus_ipa: str, coda_spelling: str, medial: bool,
             nucleus_spelling: str = "") -> str | None:
    """Nucleus + coda, with the Hanoi coda allophony applied. ``None`` when
    the combination violates the glide phonotactics."""
    coda, _checked = CODAS[coda_spelling]
    v = nucleus_ipa
    if coda_spelling in ("nh", "ch") and v == "a":
        v = "ɛ"          # ⟨anh ach⟩ are [ɛŋ ɛk]
    if coda_spelling in ("y", "u") and v == "a":
        v = "ă"          # ⟨ay au⟩ spell the short vowel
    if coda_spelling in ("ng", "c") and v == "ɛ":
        # ⟨eng ec⟩ are the long [ɛː] of Kirby's xẻng. The fronted ⟨anh
        # ach⟩ reach this point with the same /ɛ/ but a ⟨nh ch⟩ spelling,
        # and they are the SHORT member of his pair, so they stay out.
        v = "ɛː"
    if coda in ("ŋ", "k") and v in ROUNDED_MONOPHTHONGS:
        coda = "ŋ͡m" if coda == "ŋ" else "k͡p"
    if coda == "j" and v in FRONT_UNROUNDED:
        return None
    if coda == "w" and v in ROUNDED:
        return None
    return ("w" if medial else "") + v + coda


def toned(spelling: str, mark_index: int, mark: str) -> str:
    """Put a combining tone *mark* on letter *mark_index* of *spelling*."""
    if not mark:
        return spelling
    chars = list(unicodedata.normalize("NFC", spelling))
    chars[mark_index] = unicodedata.normalize(
        "NFC", chars[mark_index] + mark)
    return unicodedata.normalize("NFC", "".join(chars))


def build_graphemes() -> dict:
    graphemes: dict[str, list[str]] = {}

    def add(key: str, value: str) -> None:
        graphemes.setdefault(key, [])
        if value not in graphemes[key]:
            graphemes[key].append(value)

    for spelling, ipa in ONSETS.items():
        add(spelling, ipa)

    plain = [(n, codas, None) for n, codas in RIMES.items()]
    medial = [(m + n, codas, len(m))
              for (m, n), codas in MEDIAL_RIMES.items()]

    for nucleus_spelling, codas, medial_len in plain + medial:
        nucleus = nucleus_spelling[medial_len:] if medial_len else \
            nucleus_spelling
        nucleus_ipa, offset = NUCLEI[nucleus]
        mark_index = (medial_len or 0) + offset
        for coda_spelling in codas:
            body = rime_ipa(nucleus_ipa, coda_spelling, bool(medial_len),
                            nucleus)
            if body is None:
                continue
            checked = CODAS[coda_spelling][1]
            spelling = nucleus_spelling + coda_spelling
            for _name, mark, open_tone, checked_tone in TONES:
                tone = checked_tone if checked else open_tone
                if tone is None:
                    continue
                add(toned(spelling, mark_index, mark), body + tone)
                # Pre-reform spellings mark the medial of an open
                # ⟨oa oe uy⟩ rime instead of its nucleus (⟨hòa⟩ beside
                # ⟨hoà⟩); both are current in running text.
                if medial_len and coda_spelling == "" and mark:
                    add(toned(spelling, 0, mark), body + tone)
                # ⟨oo⟩ is written with the mark on either ⟨o⟩.
                if nucleus_spelling == "oo" and mark:
                    add(toned(spelling, 0, mark), body + tone)
                # ⟨gi⟩ + an ⟨i⟩-initial rime, written with one ⟨i⟩. The
                # key is the onset's ⟨g⟩ followed by the whole rime, so a
                # coda can never be split off it (⟨gìn⟩ is one token).
                if (not medial_len and nucleus in GI_MERGED_NUCLEI
                        and coda_spelling not in
                        GI_MERGE_EXCLUDED.get(nucleus, ())):
                    add("g" + toned(spelling, mark_index, mark),
                        "z" + body + tone)
    return graphemes


#: The Hanoi phoneme inventory (Kirby 2011), keyed to its surface forms.
#: The two doubly articulated finals are allophones of /k ŋ/, not separate
#: phonemes, which is why they are listed under them.
ALLOPHONES = {
    "ɓ": ["ɓ"], "ɗ": ["ɗ"], "t": ["t"], "tʰ": ["tʰ"], "tɕ": ["tɕ"],
    "k": ["k", "k͡p"], "m": ["m"], "n": ["n"], "ɲ": ["ɲ"],
    "ŋ": ["ŋ", "ŋ͡m"], "f": ["f"], "v": ["v"], "s": ["s"], "z": ["z"],
    "x": ["x"], "ɣ": ["ɣ"], "h": ["h"], "l": ["l"], "p": ["p"],
    "w": ["w"], "j": ["j"],
    "i": ["i"], "e": ["e"], "ɛ": ["ɛ"], "ɯ": ["ɯ"], "ɤ": ["ɤ"],
    "ɤ̆": ["ɤ̆"], "a": ["a"], "ă": ["ă"], "u": ["u"], "o": ["o"],
    "ɔ": ["ɔ"], "ɛː": ["ɛː"], "ɔː": ["ɔː"],
    "iə": ["iə"], "uə": ["uə"], "ɯə": ["ɯə"],
}


def main() -> None:
    with open(DATA, encoding="utf-8") as fh:
        spec = json.load(fh)
    graphemes = build_graphemes()
    spec["graphemes"] = {k: graphemes[k] for k in sorted(graphemes)}
    spec["allophones"] = dict(ALLOPHONES)
    with open(DATA, "w", encoding="utf-8") as fh:
        json.dump(spec, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    print(f"{len(graphemes)} grapheme keys, {len(spec['allophones'])} "
          f"allophone keys")


if __name__ == "__main__":
    main()
